using managed identity

diff --git a/azure-pipelines.yml b/azure-pipelines.yml
--- a/azure-pipelines.yml
+++ b/azure-pipelines.yml
@@ -165,7 +165,7 @@ jobs:
           --dns-name mylinuxvm-dns
 
     - task: AzureCLI@2
-      displayName: 'Give permissions to the principal'
+      displayName: 'Give permissions to the service principal'
       inputs:
         azureSubscription: $(azureSubscription)
         scriptType: bash
@@ -187,6 +187,29 @@ jobs:
             echo "🔹 Assigning role to $STORAGE_ACCOUNT..."
             az role assignment create --assignee-object-id $(AZURE_OBJECT_ID) --role "Storage Blob Data Contributor" --scope "$SCOPE" --assignee-principal-type ServicePrincipal || { echo "Failed to assign role to $STORAGE_ACCOUNT"; exit 1; }
             
+          done
+
+    - task: AzureCLI@2
+      displayName: 'Give permissions to the Managed Identity'
+      inputs:
+        azureSubscription: $(azureSubscription)
+        scriptType: bash
+        scriptLocation: inlineScript
+        inlineScript: |
+          # Define variables
+          STORAGE_ACCOUNTS=("ozstorageaccounta" "ozstorageaccountb")
+          MANAGED_IDENTITY_OBJECT_ID=$(az identity show --name <Your_Managed_Identity_Name> --resource-group <Your_Resource_Group> --query principalId --output tsv)
+
+          echo "Giving the Managed Identity the Storage Blob Data Contributor role..."         
+          
+          # Assign the Contributor role at the subscription level
+          echo "Assigning the Contributor role at the subscription level..."
+          az role assignment create --assignee-object-id "$MANAGED_IDENTITY_OBJECT_ID" --role Contributor --scope /subscriptions/$(SUBSCRIPTION_ID) --assignee-principal-type ServicePrincipal
+
+          for STORAGE_ACCOUNT in "${STORAGE_ACCOUNTS[@]}"; do
+            SCOPE="/subscriptions/$(SUBSCRIPTION_ID)/resourceGroups/$(resourceGroup)/providers/Microsoft.Storage/storageAccounts/$STORAGE_ACCOUNT"
+            echo "🔹 Assigning role to $STORAGE_ACCOUNT..."
+            az role assignment create --assignee-object-id "$MANAGED_IDENTITY_OBJECT_ID" --role "Storage Blob Data Contributor" --scope "$SCOPE" --assignee-principal-type ServicePrincipal || { echo "Failed to assign role to $STORAGE_ACCOUNT"; exit 1; }
           done
 
     - task: SSH@0
@@ -246,6 +269,8 @@ jobs:
 
           echo "Logging in to Azure CLI..."
           az login --service-principal -u "$(AZURE_APP_ID)" -p "$(AZURE_PASSWORD)" --tenant "$(AZURE_TENANT_ID)"
+          echo "Logging in to azure with managed identity"
+          az login --identity -u "$(AZURE_OBJECT_ID)" --allow-no-subscriptions
 
           echo "Changing file permissions to make the script executable..."
           sudo chmod +x /home/$(vmUsername)/blob_migration.ps1
