fix

diff --git a/azure-pipelines.yml b/azure-pipelines.yml
--- a/azure-pipelines.yml
+++ b/azure-pipelines.yml
@@ -77,44 +77,44 @@ jobs:
   # dependsOn: DeployResources
   displayName: 'Blob Migration Job'
   steps:
-    # - task: AzureCLI@2
-    #   displayName: 'Copy blob_migration.ps1 to VM'
-    #   inputs:
-    #     azureSubscription: $(azureSubscription)
-    #     scriptType: bash
-    #     scriptLocation: inlineScript
-    #     inlineScript: |
-    #       # Define VM details and the local script path
-    #       echo "resourceGroup: $(resourceGroup) vmName: $(vmName) vmUsername: $(vmUsername)"
-    #       echo "Fetching VM IP..."
-    #       VM_IP=$(az vm show -d -g $(resourceGroup) -n $(vmName) --query "publicIps" -o tsv)
-    #       echo "VM_IP: $VM_IP"
+    - task: AzureCLI@2
+      displayName: 'Copy blob_migration.ps1 to VM'
+      inputs:
+        azureSubscription: $(azureSubscription)
+        scriptType: bash
+        scriptLocation: inlineScript
+        inlineScript: |
+          # Define VM details and the local script path
+          echo "resourceGroup: $(resourceGroup) vmName: $(vmName) vmUsername: $(vmUsername)"
+          echo "Fetching VM IP..."
+          VM_IP=$(az vm show -d -g $(resourceGroup) -n $(vmName) --query "publicIps" -o tsv)
+          echo "VM_IP: $VM_IP"
 
-    #       if [ -z "$VM_IP" ]; then
-    #         echo "ERROR: Failed to retrieve VM public IP."
-    #         exit 1
-    #       fi
+          if [ -z "$VM_IP" ]; then
+            echo "ERROR: Failed to retrieve VM public IP."
+            exit 1
+          fi
 
-    #       LOCAL_SCRIPT_PATH="$(Build.SourcesDirectory)/blob_migration.ps1"
-    #       REMOTE_PATH="/home/$(vmUsername)/blob_migration.ps1"
+          LOCAL_SCRIPT_PATH="$(Build.SourcesDirectory)/blob_migration.ps1"
+          REMOTE_PATH="/home/$(vmUsername)/blob_migration.ps1"
 
-    #       # Copy the script to the VM using SCP
-    #       scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -v -i ~/.ssh/id_ed25519 "$LOCAL_SCRIPT_PATH" $(vmUsername)@$VM_IP:"$REMOTE_PATH"
-    #       # scp -v -i ~/.ssh/id_ed25519 $LOCAL_SCRIPT_PATH $(vmUsername)@$VM_IP:$REMOTE_PATH
+          # Copy the script to the VM using SCP
+          scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -v -i ~/.ssh/id_ed25519 "$LOCAL_SCRIPT_PATH" $(vmUsername)@$VM_IP:"$REMOTE_PATH"
+          # scp -v -i ~/.ssh/id_ed25519 $LOCAL_SCRIPT_PATH $(vmUsername)@$VM_IP:$REMOTE_PATH
 
-    # - task: AzureCLI@2
-    #   displayName: 'Enable a Public DNS Name for VM'
-    #   inputs:
-    #     azureSubscription: $(azureSubscription)
-    #     scriptType: bash
-    #     scriptLocation: inlineScript
-    #     inlineScript: |
-    #       # Define VM details
-    #       echo "resourceGroup: $(resourceGroup) vmName: $(vmName)"
-    #       az network public-ip update \
-    #       --resource-group $(resourceGroup) \
-    #       --name MyPublicIP \
-    #       --dns-name mylinuxvm-dns
+    - task: AzureCLI@2
+      displayName: 'Enable a Public DNS Name for VM'
+      inputs:
+        azureSubscription: $(azureSubscription)
+        scriptType: bash
+        scriptLocation: inlineScript
+        inlineScript: |
+          # Define VM details
+          echo "resourceGroup: $(resourceGroup) vmName: $(vmName)"
+          az network public-ip update \
+          --resource-group $(resourceGroup) \
+          --name MyPublicIP \
+          --dns-name mylinuxvm-dns
   
     - task: SSH@0
       displayName: 'Run PowerShell script on VM'
