fix

diff --git a/azure-pipelines.yml b/azure-pipelines.yml
--- a/azure-pipelines.yml
+++ b/azure-pipelines.yml
@@ -24,103 +24,103 @@ variables:
   value: 'b5692eb3-36bc-44f3-bead-3bb1b09d4117'
 
 jobs:
-# - job: DeployResources
-#   displayName: 'Deploy Resources (Network, Storage, and VM)'
-#   steps:
+- job: DeployResources
+  displayName: 'Deploy Resources (Network, Storage, and VM)'
+  steps:
 
-#   - task: AzureCLI@2
-#     displayName: 'Register Microsoft.Storage Provider'
-#     inputs:
-#       azureSubscription: $(azureSubscription)
-#       scriptType: 'bash'
-#       scriptLocation: 'inlineScript'
-#       inlineScript: |
-#         az provider register --namespace Microsoft.Storage
-#         az provider show --namespace Microsoft.Storage --query "registrationState"
+  - task: AzureCLI@2
+    displayName: 'Register Microsoft.Storage Provider'
+    inputs:
+      azureSubscription: $(azureSubscription)
+      scriptType: 'bash'
+      scriptLocation: 'inlineScript'
+      inlineScript: |
+        az provider register --namespace Microsoft.Storage
+        az provider show --namespace Microsoft.Storage --query "registrationState"
 
-#   - task: AzureCLI@2
-#     displayName: 'Deploy Network Resources'
-#     inputs:
-#       azureSubscription: $(azureSubscription)
-#       scriptType: bash
-#       scriptLocation: inlineScript
-#       inlineScript: |
-#         az deployment group create \
-#           --resource-group $(resourceGroup) \
-#           --template-file network-setup.json \
-#           --parameters @network-setup-parameters.json \
-#           || exit 1
+  - task: AzureCLI@2
+    displayName: 'Deploy Network Resources'
+    inputs:
+      azureSubscription: $(azureSubscription)
+      scriptType: bash
+      scriptLocation: inlineScript
+      inlineScript: |
+        az deployment group create \
+          --resource-group $(resourceGroup) \
+          --template-file network-setup.json \
+          --parameters @network-setup-parameters.json \
+          || exit 1
 
-#   - task: AzureCLI@2
-#     displayName: 'Deploy Virtual Machine'
-#     inputs:
-#       azureSubscription: $(azureSubscription)
-#       scriptType: bash
-#       scriptLocation: inlineScript
-#       inlineScript: |
-#         az deployment group create \
-#           --resource-group $(resourceGroup) \
-#           --template-file linux-vm.json \
-#           --parameters @linux-vm-parameters.json \
-#           --parameters sshPublicKey="$(cat ~/.ssh/id_ed25519.pub)" \
-#           || exit 1
+  - task: AzureCLI@2
+    displayName: 'Deploy Virtual Machine'
+    inputs:
+      azureSubscription: $(azureSubscription)
+      scriptType: bash
+      scriptLocation: inlineScript
+      inlineScript: |
+        az deployment group create \
+          --resource-group $(resourceGroup) \
+          --template-file linux-vm.json \
+          --parameters @linux-vm-parameters.json \
+          --parameters sshPublicKey="$(cat ~/.ssh/id_ed25519.pub)" \
+          || exit 1
 
-#   - task: AzureCLI@2
-#     displayName: 'Deploy Storage Account'
-#     inputs:
-#       azureSubscription: $(azureSubscription)
-#       scriptType: bash
-#       scriptLocation: inlineScript
-#       inlineScript: |
-#         az deployment group create \
-#           --resource-group $(resourceGroup) \
-#           --template-file storage-accounts.json \
-#           --parameters @storage-accounts-parameters.json \
-#           || exit 1
+  - task: AzureCLI@2
+    displayName: 'Deploy Storage Account'
+    inputs:
+      azureSubscription: $(azureSubscription)
+      scriptType: bash
+      scriptLocation: inlineScript
+      inlineScript: |
+        az deployment group create \
+          --resource-group $(resourceGroup) \
+          --template-file storage-accounts.json \
+          --parameters @storage-accounts-parameters.json \
+          || exit 1
 
 - job: BlobMigration
-  # dependsOn: DeployResources
+  dependsOn: DeployResources
   displayName: 'Blob Migration Job'
   steps:
-    # - task: AzureCLI@2
-    #   displayName: 'Copy blob_migration.ps1 to VM'
-    #   inputs:
-    #     azureSubscription: $(azureSubscription)
-    #     scriptType: bash
-    #     scriptLocation: inlineScript
-    #     inlineScript: |
-    #       # Define VM details and the local script path
-    #       echo "resourceGroup: $(resourceGroup) vmName: $(vmName) vmUsername: $(vmUsername)"
-    #       echo "Fetching VM IP..."
-    #       VM_IP=$(az vm show -d -g $(resourceGroup) -n $(vmName) --query "publicIps" -o tsv)
-    #       echo "VM_IP: $VM_IP"
+    - task: AzureCLI@2
+      displayName: 'Copy blob_migration.ps1 to VM'
+      inputs:
+        azureSubscription: $(azureSubscription)
+        scriptType: bash
+        scriptLocation: inlineScript
+        inlineScript: |
+          # Define VM details and the local script path
+          echo "resourceGroup: $(resourceGroup) vmName: $(vmName) vmUsername: $(vmUsername)"
+          echo "Fetching VM IP..."
+          VM_IP=$(az vm show -d -g $(resourceGroup) -n $(vmName) --query "publicIps" -o tsv)
+          echo "VM_IP: $VM_IP"
 
-    #       if [ -z "$VM_IP" ]; then
-    #         echo "ERROR: Failed to retrieve VM public IP."
-    #         exit 1
-    #       fi
+          if [ -z "$VM_IP" ]; then
+            echo "ERROR: Failed to retrieve VM public IP."
+            exit 1
+          fi
 
-    #       LOCAL_SCRIPT_PATH="$(Build.SourcesDirectory)/blob_migration.ps1"
-    #       REMOTE_PATH="/home/$(vmUsername)/blob_migration.ps1"
+          LOCAL_SCRIPT_PATH="$(Build.SourcesDirectory)/blob_migration.ps1"
+          REMOTE_PATH="/home/$(vmUsername)/blob_migration.ps1"
 
-    #       # Copy the script to the VM using SCP
-    #       scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -v -i ~/.ssh/id_ed25519 "$LOCAL_SCRIPT_PATH" $(vmUsername)@$VM_IP:"$REMOTE_PATH" || { echo "Failed to copy script"; exit 1; }
-    #       # scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -v -i ~/.ssh/id_ed25519 "$LOCAL_SCRIPT_PATH" $(vmUsername)@$VM_IP:"$REMOTE_PATH"
-    #       # scp -v -i ~/.ssh/id_ed25519 $LOCAL_SCRIPT_PATH $(vmUsername)@$VM_IP:$REMOTE_PATH
+          # Copy the script to the VM using SCP
+          scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -v -i ~/.ssh/id_ed25519 "$LOCAL_SCRIPT_PATH" $(vmUsername)@$VM_IP:"$REMOTE_PATH" || { echo "Failed to copy script"; exit 1; }
+          # scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -v -i ~/.ssh/id_ed25519 "$LOCAL_SCRIPT_PATH" $(vmUsername)@$VM_IP:"$REMOTE_PATH"
+          # scp -v -i ~/.ssh/id_ed25519 $LOCAL_SCRIPT_PATH $(vmUsername)@$VM_IP:$REMOTE_PATH
 
-    # - task: AzureCLI@2
-    #   displayName: 'Enable a Public DNS Name for VM'
-    #   inputs:
-    #     azureSubscription: $(azureSubscription)
-    #     scriptType: bash
-    #     scriptLocation: inlineScript
-    #     inlineScript: |
-    #       # Define VM details
-    #       echo "resourceGroup: $(resourceGroup) vmName: $(vmName)"
-    #       az network public-ip update \
-    #       --resource-group $(resourceGroup) \
-    #       --name MyPublicIP \
-    #       --dns-name mylinuxvm-dns
+    - task: AzureCLI@2
+      displayName: 'Enable a Public DNS Name for VM'
+      inputs:
+        azureSubscription: $(azureSubscription)
+        scriptType: bash
+        scriptLocation: inlineScript
+        inlineScript: |
+          # Define VM details
+          echo "resourceGroup: $(resourceGroup) vmName: $(vmName)"
+          az network public-ip update \
+          --resource-group $(resourceGroup) \
+          --name MyPublicIP \
+          --dns-name mylinuxvm-dns
 
     - task: AzureCLI@2
       displayName: 'Give permissions to the principal'
@@ -132,14 +132,7 @@ jobs:
           # Define variables
           STORAGE_ACCOUNTS=("ozstorageaccounta" "ozstorageaccountb")
 
-          echo "Giving the principal the Storage Blob Data Contributor role..."
-          # Capture the principal ID
-          # principal_ID=$(az account show --query user.name -o tsv)
-          
-          #SP_OBJECT_ID=$(az ad sp list --display-name MyDevOpsServicePrincipal --query "[].id" -o tsv)
-          #echo "Service Principal Object ID: $SP_OBJECT_ID"
-
-
+          echo "Giving the principal the Storage Blob Data Contributor role..."         
           # Assign the Contributor role at the subscription level
           echo "Assigning the Contributor role at the subscription level..."
           az role assignment create --assignee-object-id $(AZURE_OBJECT_ID) --role Contributor --scope /subscriptions/b5692eb3-36bc-44f3-bead-3bb1b09d4117 --assignee-principal-type ServicePrincipal
@@ -165,6 +158,7 @@ jobs:
 
           echo "Checking if PowerShell is installed..."
           if ! command -v pwsh &> /dev/null; then
+            export DEBIAN_FRONTEND=noninteractive
             echo "PowerShell not found. Installing..."
             sudo apt-get update -qq
             sudo apt-get install -yq wget apt-transport-https software-properties-common
@@ -178,6 +172,7 @@ jobs:
 
           echo "Checking if Azure CLI is installed..."
           if ! command -v az &> /dev/null; then
+            export DEBIAN_FRONTEND=noninteractive
             echo "Azure CLI not found. Installing..."
             sudo apt-get update -qq
             sudo apt-get install -yq azure-cli
