fix

diff --git a/azure-pipelines.yml b/azure-pipelines.yml
--- a/azure-pipelines.yml
+++ b/azure-pipelines.yml
@@ -137,7 +137,7 @@ jobs:
 
           # Assign the Contributor role at the subscription level
           echo "Assigning the Contributor role at the subscription level..."
-          az role assignment create --assignee $principal_ID --role Contributor --scope /subscriptions/b5692eb3-36bc-44f3-bead-3bb1b09d4117
+          az role assignment create --assignee $principal_ID --role Contributor --scope /subscriptions/b5692eb3-36bc-44f3-bead-3bb1b09d4117 --assignee-principal-type ServicePrincipal
           # az role assignment create --assignee 6f3fa905-ebcf-4c1b-8bda-29c03412a289 --role "User Access Administrator" --scope /subscriptions/b5692eb3-36bc-44f3-bead-3bb1b09d4117
           # az role assignment create --assignee $principal_ID --role Contributor --scope /subscriptions/$(subscriptionId)
 
@@ -147,7 +147,7 @@ jobs:
             echo "Scope: $SCOPE"  # Debugging line to print scope
 
             echo "🔹 Assigning role to $STORAGE_ACCOUNT..."
-            az role assignment create --assignee "$principal_ID" --role "Storage Blob Data Contributor" --scope "$SCOPE" || { echo "Failed to assign role to $STORAGE_ACCOUNT"; exit 1; }
+            az role assignment create --assignee "$principal_ID" --role "Storage Blob Data Contributor" --scope "$SCOPE" --assignee-principal-type ServicePrincipal || { echo "Failed to assign role to $STORAGE_ACCOUNT"; exit 1; }
             
           done
 
