add more alerts

diff --git a/azure-pipelines.yml b/azure-pipelines.yml
--- a/azure-pipelines.yml
+++ b/azure-pipelines.yml
@@ -22,6 +22,8 @@ variables:
   value: 'MyLinuxVM'
 - name: AdminEmail
   value: 'ozblech87@gmail.com'
+- name: actionGroupAlerts
+  value: 'AlertsActionGroup'
 
 jobs:
 - job: CreateManagedIdentity
@@ -171,7 +173,7 @@ jobs:
           REMOTE_PATH="/home/$(vmUsername)/blob_migration.ps1"
 
           # Copy the script to the VM using SCP
-          scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -v -i ~/.ssh/id_ed25519 "$LOCAL_SCRIPT_PATH" $(vmUsername)@$VM_IP:"$REMOTE_PATH" || { echo "Failed to copy script"; exit 1; }
+          scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -v -i $(privateKey) "$LOCAL_SCRIPT_PATH" $(vmUsername)@$VM_IP:"$REMOTE_PATH" || { echo "Failed to copy script"; exit 1; }
 
     - task: AzureCLI@2
       displayName: 'Enable a Public DNS Name for VM'
@@ -283,10 +285,10 @@ jobs:
 
 - job: CreateAlert
   dependsOn: DeployResources
-  displayName: 'Create Storage Account Capacity Alert'
+  displayName: 'Create Account Alerts'
   steps:
   - task: AzureCLI@2
-    displayName: "Create Action Group for Storage Alerts"
+    displayName: "Create Action Group for Alerts"
     inputs:
       azureSubscription: $(azureSubscription)
       scriptType: "bash"
@@ -294,8 +296,8 @@ jobs:
       inlineScript: |
         az monitor action-group create \
           --resource-group $(resourceGroup) \
-          --name "StorageAlerts" \
-          --short-name "StorageAG" \
+          --name $(actionGroupAlerts) \
+          --short-name "GeneralAG" \
           --action email "AdminEmail" $(AdminEmail) \
 
   - task: AzureCLI@2
@@ -316,7 +318,25 @@ jobs:
                 --severity 3 \
                 --window-size "PT1H" \
                 --action "/subscriptions/$(SUBSCRIPTION_ID)/resourceGroups/$(resourceGroup)/providers/microsoft.insights/actionGroups/StorageAlerts"
+                --action-group $(actionGroupAlerts)
         done
+  - task: AzureCLI@2
+    displayName: "Create Blob Transactions Anomaly Alert"
+    inputs:
+      azureSubscription: $(azureSubscription)
+      scriptType: "bash"
+      scriptLocation: "inlineScript"
+      inlineScript: |
+        for storageAccount in "ozstorageaccounta" "ozstorageaccountb"; do
+            # Create alert for when UsedCapacity exceeds 80% of TotalCapacity
+            az monitor metrics alert create \
+            --name "BlobTransactionSpikeAlert-$storageAccount" \
+            --resource-group $(resourceGroup) \
+            --scopes "/subscriptions/$(SUBSCRIPTION_ID)/resourceGroups/$(resourceGroup)/providers/Microsoft.Storage/storageAccounts/$storageAccount" \
+            --condition "total Transactions > 10000" \
+            --description "Unexpected increase in blob transactions" \
+            --action-group $(actionGroupAlerts)
+          done
   - task: AzureCLI@2
     displayName: "Create VM CPU Usage Alert"
     inputs:
@@ -334,7 +354,37 @@ jobs:
             --severity 3 \
             --window-size "PT1H" \
             --action "/subscriptions/$(SUBSCRIPTION_ID)/resourceGroups/$(resourceGroup)/providers/microsoft.insights/actionGroups/StorageAlerts"
-
+            --action-group $(actionGroupAlerts)
+  - task: AzureCLI@2
+    displayName: "Create VM Low Disk Space Alert"
+    inputs:
+      azureSubscription: $(azureSubscription)
+      scriptType: "bash"
+      scriptLocation: "inlineScript"
+      inlineScript: |
+        # Create alert for Low Disk Space Alert on the VM
+        az monitor metrics alert create \
+        --name "LowDiskSpaceAlert" \
+        --resource-group $(resourceGroup) \
+        --scopes "/subscriptions/$(SUBSCRIPTION_ID)/resourceGroups/$(resourceGroup)/providers/Microsoft.Compute/virtualMachines/$(vmName)" \
+        --condition "total LogicalDiskFreeSpace < 10%" \
+        --description "Disk space is critically low" \
+        --action-group $(actionGroupAlerts)
+  - task: AzureCLI@2
+    displayName: "Create Suspicious Traffic Alert (DDoS Protection)"
+    inputs:
+      azureSubscription: $(azureSubscription)
+      scriptType: "bash"
+      scriptLocation: "inlineScript"
+      inlineScript: |
+        # Create alert for Suspicious Traffic Alert (DDoS Protection)
+        az monitor metrics alert create \
+        --name "DDoSAttackAlert" \
+        --resource-group $(resourceGroup) \
+        --scopes "/subscriptions/$(SUBSCRIPTION_ID)/resourceGroups/$(resourceGroup)/providers/Microsoft.Network/networkSecurityGroups/MyNetworkSecurityGroup" \
+        --condition "total InboundTraffic > 100MB" \
+        --description "Possible DDoS attack detected" \
+        --action-group $(actionGroupAlerts)
 - job: CreateDashboard
   displayName: 'Create Dashboard for Monitoring'
   dependsOn: CreateAlert
